title: sunlightmap
email: cprior@gmail.com
description: >- 
  Shows a day- and night map of the planet
description_de: >- # this means to ignore newlines until "baseurl:"
  Zeigt eine Tag- und Nachtkarte des Planeten
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

source:        .
layouts_dir:  ./business/marketing/website/_layouts
includes_dir: ./business/marketing/website/_includes
destination:  ./business/marketing/website/_site
data_dir:     ./data
sass:
    sass_dir: ./business/marketing/website/assets/_sass

exclude:
  - application/physical/mobileapp
  - application/physical/backend/README.md